BACKGROUND = (255, 255, 255)
WIDTH = 800
HEIGHT = 600

# Boundary constants
LEFT_BOUNDARY = 2
RIGHT_BOUNDARY = 4
TOP_BOUNDARY = 8
BOTTOM_BOUNDARY = 16

BOUNDARIES = (LEFT_BOUNDARY, RIGHT_BOUNDARY, TOP_BOUNDARY, BOTTOM_BOUNDARY)